export const SERVICES_LIST = [
    {
        "title":"Web Developer",
        "text":"I am an intermediate web application developer with solid experience in developing modern web applications. I specialize in using React and Flutter, which allows me to build dynamic and responsive applications for both web and mobile platforms. My knowledge of Tailwind CSS and CSS itself enables me to effectively create aesthetically pleasing and functional user interfaces that conform to specific requirements. I am constantly developing my skills that I will be able to use to create innovative web applications. ",
        "more":"Et eos dolor ut consequat nisl sadipscing justo ipsum clita imperdiet aliquyam invidunt ea rebum placerat amet. Dolor duo lobortis ipsum labore ipsum invidunt gubergren sed enim duis vel amet vel no accusam lorem laoreet eum. Feugiat sit at dolor esse elitr sadipscing stet tempor consequat est ut tincidunt takimata erat. Nostrud eos nonumy ipsum nonumy vero. Eros takimata illum gubergren voluptua et et ut aliquam. Vel ipsum sit eum accusam erat sadipscing est sanctus eos sadipscing sit diam sea nulla at gubergren sed. Consequat vel consetetur et vel delenit iriure lorem ipsum sit sed accusam nonumy praesent tempor voluptua ut amet eirmod."
    },
    {
        "title":"Mobile Developer",
        "text":"I am an intermediate mobile application developer for Android and iOS platforms. I specialize in native languages such as React Native and Flutter, which allows me to build efficient and visually appealing mobile applications. Thanks to my knowledge of mobile device emulators such as Android Studio, I can effectively test and debug applications, which ensures their high quality and reliability.",
        "more":"Et eos dolor ut consequat nisl sadipscing justo ipsum clita imperdiet aliquyam invidunt ea rebum placerat amet. Dolor duo lobortis ipsum labore ipsum invidunt gubergren sed enim duis vel amet vel no accusam lorem laoreet eum. Feugiat sit at dolor esse elitr sadipscing stet tempor consequat est ut tincidunt takimata erat. Nostrud eos nonumy ipsum nonumy vero. Eros takimata illum gubergren voluptua et et ut aliquam. Vel ipsum sit eum accusam erat sadipscing est sanctus eos sadipscing sit diam sea nulla at gubergren sed. Consequat vel consetetur et vel delenit iriure lorem ipsum sit sed accusam nonumy praesent tempor voluptua ut amet eirmod."

    },
    {
        "title":"Python Developer",
        "text":"I am an intermediate Python language developer with extensive experience in developing various projects based on this technology. Over the years of working with Python, I have gained extensive knowledge and practical skills in using this particular language and have learned several popular frameworks such as tensorFlow, Pandas, Flute, etc. I can also use this language to develop backend applications using FastAPI and connect it to any database. I am very quick to learn new libraries, frameworks that use this language.",
        "more":"Et eos dolor ut consequat nisl sadipscing justo ipsum clita imperdiet aliquyam invidunt ea rebum placerat amet. Dolor duo lobortis ipsum labore ipsum invidunt gubergren sed enim duis vel amet vel no accusam lorem laoreet eum. Feugiat sit at dolor esse elitr sadipscing stet tempor consequat est ut tincidunt takimata erat. Nostrud eos nonumy ipsum nonumy vero. Eros takimata illum gubergren voluptua et et ut aliquam. Vel ipsum sit eum accusam erat sadipscing est sanctus eos sadipscing sit diam sea nulla at gubergren sed. Consequat vel consetetur et vel delenit iriure lorem ipsum sit sed accusam nonumy praesent tempor voluptua ut amet eirmod."
    },
    {
        "title":"Cybersecurity specialist",
        "text":"I am a cybersecurity specialist with expertise in protecting systems and data from threats. I am familiar with basic methodologies in the field of cybersecurity, such as OWASP, the most popular vulnerabilities, ways to secure, etc. My knowledge includes both defensive and offensive programming concepts, I have basic knowledge in performing penetration testing. I am constantly developing my skills and knowledge and participate in CTF tasks as a hobby.",
        "more":"Et eos dolor ut consequat nisl sadipscing justo ipsum clita imperdiet aliquyam invidunt ea rebum placerat amet. Dolor duo lobortis ipsum labore ipsum invidunt gubergren sed enim duis vel amet vel no accusam lorem laoreet eum. Feugiat sit at dolor esse elitr sadipscing stet tempor consequat est ut tincidunt takimata erat. Nostrud eos nonumy ipsum nonumy vero. Eros takimata illum gubergren voluptua et et ut aliquam. Vel ipsum sit eum accusam erat sadipscing est sanctus eos sadipscing sit diam sea nulla at gubergren sed. Consequat vel consetetur et vel delenit iriure lorem ipsum sit sed accusam nonumy praesent tempor voluptua ut amet eirmod."
    },
    {
        "title":"AI Developer",
        "text":"I am an AI programmer with basic knowledge of artificial intelligence, backed by IBM certifications in the field. I have hands-on skills in using machine learning libraries such as TensorFlow and scikit-learn, which allows me to create advanced models and algorithms. My experience includes working with various data types and problems, including classification, regression and data analysis. With a solid theoretical and practical foundation, I can effectively implement AI solutions.",
        "more":"Et eos dolor ut consequat nisl sadipscing justo ipsum clita imperdiet aliquyam invidunt ea rebum placerat amet. Dolor duo lobortis ipsum labore ipsum invidunt gubergren sed enim duis vel amet vel no accusam lorem laoreet eum. Feugiat sit at dolor esse elitr sadipscing stet tempor consequat est ut tincidunt takimata erat. Nostrud eos nonumy ipsum nonumy vero. Eros takimata illum gubergren voluptua et et ut aliquam. Vel ipsum sit eum accusam erat sadipscing est sanctus eos sadipscing sit diam sea nulla at gubergren sed. Consequat vel consetetur et vel delenit iriure lorem ipsum sit sed accusam nonumy praesent tempor voluptua ut amet eirmod."
    },
    
]